### ISSUE TITLE
Invalid syntax in latest version

### ISSUE THREAD

**Issue by hanxue** [vijinho/f3-boilerplate#14]
I see this when running f3-boilerplate

`( ! ) Parse error: syntax error, unexpected 'echo' (T_ECHO) in /Volumes/ramdisk/f3-boilerplate/app/app.php on line 55`

In the source code, there is no line terminator

`print "poop"`

I notice another file Cf.php also has the same syntax. 

Is this by purpose?

**Comment by vijinho** [comment]
This is fixed now, thanks!
