### ISSUE TITLE
Some resources missing

### ISSUE THREAD

**Issue by Jovian** [vijinho/f3-boilerplate#21]
Hello.

Just installed on my server to try F3 and you boilerplate.
But seems something is wrong with CSS -- Chrome Dev Tools says **basscss.min.css** is missing.
And I can't find it /www/css

Also /tmp/screenshot.png is missing. Wondering when it should be created, because i only created empty tmp dir as per instructions here...

Screenshots:
http://i.imgur.com/JGvuJta.png
http://i.imgur.com/JHIVHTu.png

Also, just to not open new issue:

in \app\templates\en\website\header.phtml there seems to be a duplicate for unkown (for me atleast) reason:

1. `<meta name="viewport" content="width=device-width, initial-scale=1">`
2. `<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0,minimal-ui">`

**Comment by vijinho** [comment]
Hi, I've removed the duplicate viewport reference and also the references to basscss, thanks!
