### ISSUE TITLE
PHP7 only?

### ISSUE THREAD

**Issue by LeftPinkie** [vijinho/f3-boilerplate#22]
Not an issue, but more of a question...
Is this truly PHP7 only?
The reason I am asking is because my web hosting service only provides PHP v5.6 (yes, I understand this is old).  Is PHP7 really a hard requirement?  Where is it using PHP7 specific codes?
Also, how do I clone this project prior to v2.2.0... if I don't want the hard PHP7 requirement?

**Comment by vijinho** [comment]
I'm afraid I'm not coding much these days and can do little to help you at this time. You might want to try this project which converts PHP7 to PHP5 on this project.
https://github.com/spatie/7to5
