### ISSUE TITLE
Warning: require_once(../vendor/bcosca/fatfree/lib/base.php): failed to open stream: No such file or directory in D:\xampp\htdocs\f3-boilerplate\app\bootstrap.php on line 13

### ISSUE THREAD

**Issue by coolwidgets** [vijinho/f3-boilerplate#4]
Along with this error

Fatal error: require_once(): Failed opening required '../vendor/bcosca/fatfree/lib/base.php' (include_path='.;D:\xampp\php\PEAR') in D:\xampp\htdocs\f3-boilerplate\app\bootstrap.php on line 13

**Comment by pmller** [comment]
A little late, but: When you download the package from github the current version of Fatfreeframework itself is not included. If you add it to your project via composer that path (vendor/bcosca/fatfree) is where it will go. Of course you can also just download the .zip file of the framework and put it there.

**Comment by vijinho** [comment]
If you send a pull-request/patch I will update and give you a mention in the CREDITS :)

**Comment by pmller** [comment]
Sure thing, should happen later today. Maybe with a bit of documentation on why someone might still want to gitignore the stuff managed by composer when using that. 

Patrick Müller
Am Beckers Busch 12
42799 Leichlingen

T +492175979802
patrick@pmller.de

**Comment by vijinho** [comment]
Merged fix from pmiller, so closing.
